# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f00668a23016dd60868176b9c1fa134ed30cba50a37c249a80b4dd85f66c66d090a7696b46b5a7851fc67b5416d258511d076120493828ce5dc2e178620b9b59

test:
  secret_key_base: f2f92fb3f81fa4e8653f3320e43631d7369aa88288d147b4bde3e2bf725998820b6226d3451a3ab826c88dcd9b3b52701780c3dd1ef069c3ee51e04e62a4855e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
